-- Create review table
CREATE TABLE IF NOT EXISTS public.review (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_date timestamp with time zone DEFAULT now() NOT NULL,
    inv_id integer NOT NULL,
    account_id integer NOT NULL
);

-- Create primary key
ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (review_id);

-- Create foreign key relationships
ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_inv_id_fkey FOREIGN KEY (inv_id) REFERENCES public.inventory(inv_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON DELETE CASCADE;

-- Create indexes for better performance
CREATE INDEX idx_review_inv_id ON public.review(inv_id);
CREATE INDEX idx_review_account_id ON public.review(account_id);
CREATE INDEX idx_review_date ON public.review(review_date DESC);

-- Add comments
COMMENT ON TABLE public.review IS 'Stores customer reviews for inventory items';
COMMENT ON COLUMN public.review.review_text IS 'The text content of the review';
COMMENT ON COLUMN public.review.review_date IS 'When the review was submitted';
COMMENT ON COLUMN public.review.inv_id IS 'References the inventory item being reviewed';
COMMENT ON COLUMN public.review.account_id IS 'References the account that wrote the review';
